### ISSUE TITLE
[Bug]: Conflict with the latest lualine

### ISSUE THREAD

**Issue by edte** [chrisgrieser/nvim-recorder#16]
### Bug Description

the position of lualine changes from the bottom to the top

my config
```
local M = {}

-- 延迟加载
M.recoderConfig = function()
	local recoder = try_require("recorder")
	if recoder == nil then
		return
	end

	local lualine = try_require("lualine")
	if lualine == nil then
		return
	end

	recoder.setup({
		mapping = {
			startStopRecording = "q",
			playMacro = "Q",
		},
	})

	local lualineZ = lualine.get_config().sections.lualine_z or {}
	local lualineY = lualine.get_config().sections.lualine_y or {}
	table.insert(lualineZ, { recoder.recordingStatus })
	table.insert(lualineY, { recoder.displaySlots })

	lualine.setup({
		tabline = {
			lualine_y = lualineY,
			lualine_z = lualineZ,
		},
	})
end

return M
```

### Relevant Screenshot

https://github.com/chrisgrieser/nvim-recorder/assets/50194671/661131a8-8467-4ccb-be67-92f31e104dff

### To Reproduce

Reproduction steps
1. Install the latest lualine and nvim-recoder
2. press q, q
3. switch another buffer

### neovim version

```Text
$ lvim --version
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
As far as I can tell, that is an issue related to lualine and not this plugin. The plugin does not do anything special in its statusline components that works differently from dozens of other plugins that offer statusline components.

Using the tabline is generally a bit error-prone, since depending on your lualine- and tab config, the tabline may disappear/change. I'd try using the statusline or the winbar. If that does not help, I recommend opening an issue at the lualine repo.
