### ISSUE TITLE
Feature Request: Colored statusline components

### ISSUE THREAD

**Issue by al1-ce** [chrisgrieser/nvim-recorder#17]
### Checklist

- [X] I have read the plugin's documentation.
- [X] The feature would be useful to more users than just me.

### Feature Requested

Allow lualine recordingStatus to be red when recording

Can be useful with disabled notifications

**Comment by chrisgrieser** [comment]
That can be achieved with lualine's `color` component option (Using the `Error` highlight group here, since it's always red whatever your theme is, for more coloring options, [see the lualine-docs on component options](https://github.com/nvim-lualine/lualine.nvim?tab=readme-ov-file#general-component-options))

```lua
lualine_z = {
	{ require("recorder").recordingStatus, color = "Error" },
},
```
